basePath: /api/v1
definitions:
  ApiResponse:
    properties:
      body:
        properties:
          email:
            type: string
          id:
            type: string
        type: object
      message:
        type: string
      status:
        type: integer
    type: object
  GroupedTransactionsResponse:
    properties:
      accounts:
        type: array
        items:
          type: object
          properties:
            accountId:
              type: string
            balance:
              type: number
              description: Solde du compte à la fin du mois
            transactions:
              type: array
              items:
                $ref: '#/definitions/Transaction'
    type: object
    description: Réponse contenant les transactions du mois en cours groupées par
      compte bancaire.
  Login:
    properties:
      email:
        description: user email
        type: string
      password:
        description: user password
        type: string
  LoginResponse:
    properties:
      token:
        type: string
    type: object
  Transaction:
    properties:
      date:
        type: string
        format: date-time
        description: Date de la transaction
      description:
        type: string
        description: Description de la transaction
      amount:
        type: number
        description: Montant de la transaction
      balance:
        type: number
        description: Solde du compte après la transaction
      type:
        type: string
        enum:
        - deposit
        - withdrawal
        description: Type de transaction (dépôt ou retrait)
      category:
        type: string
        description: Catégorie de la transaction
      notes:
        type: string
        description: Notes additionnelles de l'utilisateur
    type: object
  User:
    properties:
      email:
        description: user email
        type: string
      firstName:
        description: user first name
        type: string
      lastName:
        description: user last name
        type: string
      password:
        description: user password
        type: string
  UserProfile:
    properties:
      firstName:
        type: string
      lastName:
        type: string
    type: object
host: localhost:3001
info:
  description: Contains all available API endpoints in this codebase
  termsOfService: http://swagger.io/terms/
  title: Bank Argent API documentation
  version: 1.0.0
paths:
  /transactions:
    get:
      description: Récupère les transactions du mois en cours, groupées par compte
        bancaire.
      parameters: []
      produces:
      - application/json
      responses:
        '200':
          description: Transactions récupérées avec succès
          schema:
            $ref: '#/definitions/GroupedTransactionsResponse'
        '401':
          description: 'Non autorisé : token d''authentification manquant ou invalide'
      summary: Transactions mensuelles groupées par compte
      tags:
      - Transaction Module
      security:
      - Bearer: []
  /transactions/{transactionId}:
    get:
      description: Retourne les détails d'une transaction spécifique.
      parameters:
      - in: path
        name: transactionId
        required: true
        type: string
      responses:
        '200': &id001
          description: Transaction avec solde
          schema:
            $ref: '#/definitions/Transaction'
        '404':
          description: Transaction introuvable
      summary: Obtenir les détails d'une transaction
      tags:
      - Transaction Module
    put:
      description: Met à jour uniquement la catégorie et les notes d'une transaction
        existante.
      parameters:
      - name: transactionId
        in: path
        required: true
        type: string
      - in: body
        name: body
        required: true
        schema:
          type: object
          properties:
            category:
              type: string
              description: Catégorie de la transaction
            notes:
              type: string
              description: Notes additionnelles de l'utilisateur
          required:
          - category
      responses:
        '200': *id001
        '404':
          description: Transaction introuvable
      summary: Modifier une transaction (catégorie et notes seulement)
      tags:
      - Transaction Module
  /user/login:
    post:
      description: API for Login
      parameters:
      - description: Login Payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/Login'
      produces:
      - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
      summary: Login
      tags:
      - User Module
  /user/profile:
    post:
      description: API for fetching a user profile
      parameters:
      - description: Attach Bearer JWT token
        in: header
        name: Authorization
        required: true
      produces:
      - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
      security:
      - Bearer: []
      summary: User Profile API
      tags:
      - User Module
    put:
      description: API for updating a user profile
      parameters:
      - description: Attach Bearer JWT token
        in: header
        name: Authorization
        required: true
      - description: Update user profile attributes
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/UserProfile'
      produces:
      - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
      security:
      - Bearer: []
      summary: User Profile API
      tags:
      - User Module
  /user/signup:
    post:
      description: API for Signup
      parameters:
      - description: Signup Payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/User'
      produces:
      - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
      summary: Signup
      tags:
      - User Module
schemes:
- http
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: '2.0'
